# Stages run sequentially, so we add a new `deploy` stage 
# after the `build` one
stages:
  - build
  - deploy

build:
  image: node:latest    
  stage: build
  script:
    - yarn install      
    - CI=false yarn build:prod
    - sed -i "s/=\"\//=\"/g" build/index.html
    - cp build/index.html build/404.html
  artifacts:
    paths:
      - build/

pages:
  image: alpine:latest
  stage: deploy
  variables: 
    # Replace this with your site URL
    PUBLIC_URL: https://entri.gitlab.io/entri-game/
  variables:
    GIT_STRATEGY: none        # Do not clone git repo
  script:
    # Rename the CRA `build` folder to `public`
    - mv build public         
  artifacts:
    paths:
      - public/
